// <auto-generated />
using System;
using CitizenConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitizenConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602131108_AddOfficerCategoryMappings")]
    partial class AddOfficerCategoryMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Demographic", b =>
                {
                    b.Property<int>("DemographicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DemographicId"));

                    b.Property<int>("ChildPopulation")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FemaleLiteracyRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FemalePopulation")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JurisdictionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaleLiteracyRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MalePopulation")
                        .HasColumnType("int");

                    b.Property<int>("SeniorCitizenPopulation")
                        .HasColumnType("int");

                    b.Property<int>("SurveyYear")
                        .HasColumnType("int");

                    b.Property<int>("TotalHouseholds")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalLiteracyRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalPopulation")
                        .HasColumnType("int");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("DemographicId");

                    b.HasIndex("JurisdictionId");

                    b.HasIndex("WardId");

                    b.ToTable("Demographics");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityData", b =>
                {
                    b.Property<int>("FacilityDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityDataId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityFieldId")
                        .HasColumnType("int");

                    b.Property<int>("FacilityModuleId")
                        .HasColumnType("int");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JurisdictionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("FacilityDataId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FacilityFieldId");

                    b.HasIndex("FacilityModuleId");

                    b.HasIndex("JurisdictionId");

                    b.HasIndex("WardId");

                    b.HasIndex("JurisdictionId", "WardId", "FacilityModuleId");

                    b.HasIndex("JurisdictionId", "WardId", "FacilityModuleId", "FacilityFieldId")
                        .IsUnique()
                        .HasFilter("[WardId] IS NOT NULL");

                    b.ToTable("FacilityDatas");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityField", b =>
                {
                    b.Property<int>("FacilityFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FacilityModuleId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FieldType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FacilityFieldId");

                    b.HasIndex("FacilityModuleId", "FieldName")
                        .IsUnique();

                    b.ToTable("FacilityFields");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityFieldOption", b =>
                {
                    b.Property<int>("FacilityFieldOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityFieldOptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FacilityFieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FacilityFieldOptionId");

                    b.HasIndex("FacilityFieldId", "OptionText")
                        .IsUnique();

                    b.ToTable("FacilityFieldOptions");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityModule", b =>
                {
                    b.Property<int>("FacilityModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityModuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FacilityModuleId");

                    b.HasIndex("ModuleName")
                        .IsUnique();

                    b.ToTable("FacilityModules");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Jurisdiction", b =>
                {
                    b.Property<int>("JurisdictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JurisdictionId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JurisdictionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("JurisdictionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Pincode")
                        .HasColumnType("char(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JurisdictionId");

                    b.HasIndex("JurisdictionName")
                        .IsUnique();

                    b.HasIndex("JurisdictionTypeId");

                    b.ToTable("Jurisdictions");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Locality", b =>
                {
                    b.Property<int>("LocalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalityTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("LocalityId");

                    b.HasIndex("LocalityTypeId");

                    b.HasIndex("WardId");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoterRegistered")
                        .HasColumnType("bit");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("int");

                    b.Property<int>("ResidenceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("CitizenId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("ResidenceTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WardId");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComplaintStatusMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("ComplaintId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ComplaintCategoryId");

                    b.HasIndex("ComplaintNumber")
                        .IsUnique();

                    b.HasIndex("ComplaintStatusMasterId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("WardId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintImage", b =>
                {
                    b.Property<int>("ComplaintImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintImageId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintImageId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintImages");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintStatusHistory", b =>
                {
                    b.Property<int>("ComplaintStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintStatusHistoryId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintStatusHistories");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintStatusMaster", b =>
                {
                    b.Property<int>("ComplaintStatusMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintStatusMasterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintStatusMasterId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("ComplaintStatusMasters");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.JurisdictionType", b =>
                {
                    b.Property<int>("JurisdictionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JurisdictionTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JurisdictionDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JurisdictionTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JurisdictionTypeId");

                    b.HasIndex("JurisdictionTypeName")
                        .IsUnique();

                    b.ToTable("JurisdictionTypes");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.LocalityType", b =>
                {
                    b.Property<int>("LocalityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalityTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LocalityTypeId");

                    b.ToTable("LocalityTypes");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OfficerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.OfficerCategoryMapping", b =>
                {
                    b.Property<int>("OfficerCategoryMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerCategoryMappingId"));

                    b.Property<int>("ComplaintCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.HasKey("OfficerCategoryMappingId");

                    b.HasIndex("ComplaintCategoryId");

                    b.HasIndex("OfficerId");

                    b.ToTable("OfficerCategoryMappings");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Politician", b =>
                {
                    b.Property<int>("PoliticianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliticianId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdProofPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JurisdictionId")
                        .HasColumnType("int");

                    b.Property<int>("JurisdictionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PoliticianRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("PoliticianId");

                    b.HasIndex("GovernmentId")
                        .IsUnique();

                    b.HasIndex("JurisdictionId");

                    b.HasIndex("JurisdictionTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WardId");

                    b.ToTable("Politicians");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ResidenceType", b =>
                {
                    b.Property<int>("ResidenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenceTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ResidenceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ResidenceTypeId");

                    b.ToTable("ResidenceTypes");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Suggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionId"));

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BenefitScope")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedBenefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuggestionCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuggestionStatusMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("SuggestionId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SuggestionCategoryId");

                    b.HasIndex("SuggestionStatusMasterId");

                    b.HasIndex("WardId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionAttachment", b =>
                {
                    b.Property<int>("SuggestionAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionAttachmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionAttachmentId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("SuggestionAttachments");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionCategory", b =>
                {
                    b.Property<int>("SuggestionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionCategoryId");

                    b.ToTable("SuggestionCategories");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionStatusHistory", b =>
                {
                    b.Property<int>("SuggestionStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionStatusHistoryId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("SuggestionStatusHistories");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionStatusMaster", b =>
                {
                    b.Property<int>("SuggestionStatusMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionStatusMasterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionStatusMasterId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("SuggestionStatusMasters");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionVote", b =>
                {
                    b.Property<int>("SuggestionVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionVoteId"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpVote")
                        .HasColumnType("bit");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionVoteId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("SuggestionVotes");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsappNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNo")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JurisdictionId")
                        .HasColumnType("int");

                    b.Property<int>("JurisdictionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WardDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WardId");

                    b.HasIndex("JurisdictionId");

                    b.HasIndex("JurisdictionTypeId", "WardNumber")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.WardDepartment", b =>
                {
                    b.Property<int>("WardDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardDepartmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("WardDepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("WardId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("WardDepartments");
                });

            modelBuilder.Entity("ComplaintCategory", b =>
                {
                    b.Property<int>("ComplaintCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SLAHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintCategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ComplaintCategories");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Demographic", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.Jurisdiction", "Jurisdiction")
                        .WithMany("Demographics")
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("Demographics")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Jurisdiction");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityData", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.FacilityField", "FacilityField")
                        .WithMany("FacilityDatas")
                        .HasForeignKey("FacilityFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.API.Domain.Entities.FacilityModule", "FacilityModule")
                        .WithMany("FacilityDatas")
                        .HasForeignKey("FacilityModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.API.Domain.Entities.Jurisdiction", "Jurisdiction")
                        .WithMany("FacilityDatas")
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("FacilityDatas")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacilityField");

                    b.Navigation("FacilityModule");

                    b.Navigation("Jurisdiction");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityField", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.FacilityModule", "FacilityModule")
                        .WithMany("FacilityFields")
                        .HasForeignKey("FacilityModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityModule");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityFieldOption", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.FacilityField", "FacilityField")
                        .WithMany("FacilityFieldOptions")
                        .HasForeignKey("FacilityFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityField");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Jurisdiction", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.JurisdictionType", "JurisdictionType")
                        .WithMany()
                        .HasForeignKey("JurisdictionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JurisdictionType");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Locality", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.LocalityType", "LocalityType")
                        .WithMany("Localities")
                        .HasForeignKey("LocalityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("Localities")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalityType");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Citizen", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.Locality", null)
                        .WithMany("Citizens")
                        .HasForeignKey("LocalityId");

                    b.HasOne("CitizenConnect.Domain.Entities.ResidenceType", "ResidenceType")
                        .WithMany("Citizens")
                        .HasForeignKey("ResidenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.User", "User")
                        .WithOne("Citizen")
                        .HasForeignKey("CitizenConnect.Domain.Entities.Citizen", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("Citizens")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidenceType");

                    b.Navigation("User");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Officer", "AssignedOfficer")
                        .WithMany("Complaints")
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CitizenConnect.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Complaints")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplaintCategory", "ComplaintCategory")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.ComplaintStatusMaster", "ComplaintStatusMaster")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintStatusMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CitizenConnect.API.Domain.Entities.Locality", null)
                        .WithMany("Complaints")
                        .HasForeignKey("LocalityId");

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("Complaints")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Citizen");

                    b.Navigation("ComplaintCategory");

                    b.Navigation("ComplaintStatusMaster");

                    b.Navigation("Department");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintImage", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintImages")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintStatusHistory", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintStatusHistories")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Officer", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Department", "Department")
                        .WithMany("Officers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.OfficerCategoryMapping", b =>
                {
                    b.HasOne("ComplaintCategory", "ComplaintCategory")
                        .WithMany("OfficerCategoryMappings")
                        .HasForeignKey("ComplaintCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Officer", "Officer")
                        .WithMany("OfficerCategoryMappings")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplaintCategory");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Politician", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.Jurisdiction", null)
                        .WithMany("Politicians")
                        .HasForeignKey("JurisdictionId");

                    b.HasOne("CitizenConnect.Domain.Entities.JurisdictionType", "JurisdictionType")
                        .WithMany("Politicians")
                        .HasForeignKey("JurisdictionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.User", "User")
                        .WithOne("Politician")
                        .HasForeignKey("CitizenConnect.Domain.Entities.Politician", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("Politicians")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JurisdictionType");

                    b.Navigation("User");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Suggestion", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Suggestions")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.SuggestionCategory", "SuggestionCategory")
                        .WithMany("Suggestions")
                        .HasForeignKey("SuggestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.SuggestionStatusMaster", "SuggestionStatusMaster")
                        .WithMany("Suggestions")
                        .HasForeignKey("SuggestionStatusMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("SuggestionCategory");

                    b.Navigation("SuggestionStatusMaster");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionAttachment", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Suggestion", "Suggestion")
                        .WithMany("SuggestionAttachments")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionStatusHistory", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Suggestion", "Suggestion")
                        .WithMany("SuggestionStatusHistories")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionVote", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Citizen", "Citizen")
                        .WithMany("SuggestionVotes")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Suggestion", "Suggestion")
                        .WithMany("SuggestionVotes")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.User", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Ward", b =>
                {
                    b.HasOne("CitizenConnect.API.Domain.Entities.Jurisdiction", null)
                        .WithMany("Wards")
                        .HasForeignKey("JurisdictionId");

                    b.HasOne("CitizenConnect.Domain.Entities.JurisdictionType", "JurisdictionType")
                        .WithMany("Wards")
                        .HasForeignKey("JurisdictionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JurisdictionType");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.WardDepartment", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Department", "Department")
                        .WithMany("WardDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitizenConnect.Domain.Entities.Ward", "Ward")
                        .WithMany("WardDepartments")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("ComplaintCategory", b =>
                {
                    b.HasOne("CitizenConnect.Domain.Entities.Department", "Department")
                        .WithMany("ComplaintCategories")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityField", b =>
                {
                    b.Navigation("FacilityDatas");

                    b.Navigation("FacilityFieldOptions");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.FacilityModule", b =>
                {
                    b.Navigation("FacilityDatas");

                    b.Navigation("FacilityFields");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Jurisdiction", b =>
                {
                    b.Navigation("Demographics");

                    b.Navigation("FacilityDatas");

                    b.Navigation("Politicians");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CitizenConnect.API.Domain.Entities.Locality", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("SuggestionVotes");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Complaint", b =>
                {
                    b.Navigation("ComplaintImages");

                    b.Navigation("ComplaintStatusHistories");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ComplaintStatusMaster", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Department", b =>
                {
                    b.Navigation("ComplaintCategories");

                    b.Navigation("Complaints");

                    b.Navigation("Officers");

                    b.Navigation("WardDepartments");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.JurisdictionType", b =>
                {
                    b.Navigation("Politicians");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.LocalityType", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Officer", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("OfficerCategoryMappings");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.ResidenceType", b =>
                {
                    b.Navigation("Citizens");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Suggestion", b =>
                {
                    b.Navigation("SuggestionAttachments");

                    b.Navigation("SuggestionStatusHistories");

                    b.Navigation("SuggestionVotes");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionCategory", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.SuggestionStatusMaster", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("Citizen");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("CitizenConnect.Domain.Entities.Ward", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("Complaints");

                    b.Navigation("Demographics");

                    b.Navigation("FacilityDatas");

                    b.Navigation("Localities");

                    b.Navigation("Politicians");

                    b.Navigation("WardDepartments");
                });

            modelBuilder.Entity("ComplaintCategory", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("OfficerCategoryMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
