name: Citizen Connect Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore backend/CitizenConnectAPI/CitizenConnect.API.csproj

    - name: Build Project
      run: dotnet build backend/CitizenConnectAPI/CitizenConnect.API.csproj --configuration Release --no-restore
